version: '3'
services:

  main:
    build: .
    cap_add:
      - CAP_SYS_ADMIN
    secrets:
      - key

  dev:
    build: .
    cap_add:
      - CAP_SYS_ADMIN
    secrets:
      - key
    volumes:
      - ./:/opt/ansible:ro
      - ../images:/opt/images

secrets:
  key:
    file: ~/.ssh/id_ansible
